<h1>Uchiha Sasuke</h1>
<div class="image-wiki" style="float: right">
    <img src="wiki/Uchiha_Sasuke/sasuke_1.jpg">
</div>
<p>
    Uchiha Sasuke là một nhân vật sáng tạo xuất hiện trong bộ mânga và anime Naruto của Masashi Kisimoto. Cái tên Sasuke bắt nguồn từ một ninja huyền thoại là Sarutobi Sasuke. Họ Uchiha là Cái tên Sasuke bắt nguồn từ một ninja huyền thoại là Sarutobi Sasuke. Họ Uchiha là một cách khác để phát âm từ Uchiwa, có nghĩa là "quạt giấy". Đó còn là gia huy của bộ tộc Uchiha. Uchiwa có thể dùng để quạt lửa, khiến cho ngọn lửa nóng hơn-liên quan đến sự thật là bộ tộc Uchiha gồm những người dùng thuật lửa.
</p>
<p>
    Sasuke được sáng tác là một đối thủ và người đối nghịch với nhân vật chính của truyện, Uzumaki Naruto. Thiết kế của nhân vật khiến cho Kishimoto rất khó vẽ trong mấy cảnh manga, dù vậy anh vẫn thích vẽ Sasuke.[6][7]
</p>
<p>
    Sasuke là một thành viên của bộ tộc Uchiha, một bộ tộc ninja điêu luyện liên minh với làng Lá. Động cơ chính của cậu suốt truyện là việc báo thù sự diệt vong của toàn bộ tộc cậu ta bằng việc giết anh trai, Uchiha itachi, một nhiệm vụ mà luôn theo đuổi bằng mọi giá. Dù lúc đầu cậu có lạnh lùng và bị sự báo thù lôi kéo một cách kỳ quặc, cậu trở nên đồng cảm hơn qua những mối quan hệ với các nhân vật khác, đáng chú ý là Uzumaki Naruto, người mà cậu coi là đối thủ.
</p>
<p>
    Vài nhà sản xuất anime và manga đã ca ngợi và phê bình nhân vật Sasuke. Trong khi nhiều nhà phê bình đã lưu ý thái độ lạnh lùng và tách biệt của cậu ta, cậu được coi là một dạng "đối thủ" điển hình so với vài nhân vật khác tương tự trong manga Shonen.[8][9] Tính cách của cậu cũng là một chủ đề phê bình, khi có nhiều người cảm thấy khó khăn trong việc đồng cảm với Sasuke; IGN đã gọi đùa Sasuke là một "cậu bé trầm cảm."
</p>
<h2>Tạo dựng</h2>
<p>
    Khi phát triển manga Naruto ban đầu, Masashi Kisimoto không có ý định tạo dựng Sasuke. Sau khi nói chuyện với người biên tập của anh về tương lai bộ truyện, anh được khuyên là nên tạo một nhân vật đối nghịch với nhân vật chính, Uzumaki Naruto, nhờ vậy Sasuke được tạo dựng.[6] Để học hỏi thêm về việc tạo ra hiệu quả một đối thủ, Kishimoto đã đọc nhiều manga để thu thập thêm nhiều ý tưởng về những gì cấu thành một mối địch thù, và anh liên kết những yếu tố thiết yếu này thành một mối quan hệ. Bởi vì Sasuke sẽ đối nghịch với Naruto, Kishimoto luôn cẩn thận đảm bảo Sasuke không bao giờ quá biểu lộ cảm xúc. Với tính cách như kiểu "thiên tài trầm tĩnh" của Sasuke, Kishimoto cảm thấy anh đã tạo thành công một mối địch thù.[10]
</p>
<p>
    Thiết kế của Sasuke đã gây ra cho Kishimoto một số rắc rối, khiến cho cậu ta trở thành nhân vật khó vẽ nhât. Bởi vì anh không biết rõ ràng khuôn mặt Sasuke nên trông như thế nào, vài bản vẽ nháp của Sasuke tỏ ra quá lớn so với độ tuổi của Naruto.[11] Khi đã giải quyết khuôn mặt, Kishimoto làm việc với trang phục của Sasuke. Thiết kế ban đầu có vài dây chuyền và vòng đeo quanh tay và chân cậu, kết cục do thói quen trang hoàng nhân vật càng nhiều càng tốt của Kishimoto gây nên. Nhận ra rằng anh không thể vẽ một nhân vật phức tạp như vậy hàng tuần, Kishimoto đã đơn giản hóa trang phục sao cho tương phản với Naruto.[7]
</p>
<p>
    Với Kishimoto, Sasuke vẫn còn là nhân vật anh khó vẽ nhất. Trong khi vẽ, những lỗi rủi ro thường khiến tuổi trẻ của Sasuke biến mất, đó là do sự thiếu kinh nghiệm của Kishimoto trong vẽ nhân vật lớn trước tuổi.[7] Tóc của Sasuke, ban đầu được để ngắn để tiết kiệm thời gian cho Kishimoto, đã dần dần mọc dài hơn khi bộ truyện trôi qua, làm tăng thời gian cần thiết để vẽ Uchiha Sasuke.[11] Giữa Phần I Kishimoto vẽ một trang phục mới cho Sasuke, nó có nhiều dây thắt quanh tay và chân cậu ta. Do khoảng thời gian cần thiết để vẽ bộ này, Kishimoto đã đưa Sasuke về bộ ban đầu.[12] Mặc cho năng lượng và khối thời gian cần để vẽ Sasuke, Sasuke đã trở thành nhân vật anh ưa thích để vẽ.[7]
</p>
<p>
    Khi thiết kế Sasuke cho Phần II, nhiệm vụ chính của Kishimoto là làm cậu ta trông phải thật ngầu. Vì vậy, anh cố cho cậu ta vài bộ kiểu Shimenawa để giữ lại kiểu trang phục của Orochimaru. Anh còn cố thử bộ khác như cổ rùa và một bộ đồng phục quân đội có chữ "cleanliness". Tuy nhiên, anh kết thúc với bộ mang phong cách Nhật Bản.[13]
</p>
<h2>Đại cương nhân vật</h2>
<h4>Tiểu sử</h4>
<p>
    Thời thơ ấu của Sasuke, như đã kể trong manga Naruto tập 25, phải sống dưới bóng của anh trai mình, Uchiha Itachi, một thiên tài bẩm sinh của bộ tộc Uchiha. Để có được sự công nhận, Sasuke tập luyện cần cù để được bố mẹ chú ý, dù cậu ta vẫn chưa vượt qua được bức tường đá được anh trai cậu đặt ra.[14][15] Theo thời gian, Itachi bắt đầu xa lánh bộ tộc và không còn tâm sự với gia đình, vì vậy họ bắt đầu nhìn về Sasuke như một tương lai mới của bộ tộc.[16]
</p>
<p>
    Ngay khi Sasuke bắt đầu được gia đình chấp nhận, một ngày cậu trở về nhà và thấy đường phố đầy rẫy xác chết của người Uchiha. Khi chạy về nhà, Sasuke thấy Itachi đứng trước xác chết của bố mẹ. Lúc Sasuke định bỏ chạy, Itachi giải thích rằng anh chưa từng yêu em trai mình.[17] Khẳng định rằng Sasuke không hề đáng giết, Itachi thúc đẩy cậu phải mạnh mẽ hơn bằng cách sống một cuộc sống căm thù và oán hận, với mục đích sống duy nhất là báo thù cho bộ tộc. Itachi bỏ đi, và khi thiếu vắng một gia đình yêu thương Sasuke đã làm như được bảo, dâng cả mạng sống mình để giết Itachi.[18] Mấy năm sau, Sasuke tốt nghiệp Học viện Ninja, trở thành một thành viên trong Đội 7 cùng Uzumaki Naruto, Haruno Sakura va Hatake Kakashi. Trong cuộc thi ninja Trung đẳng, Sasuke và đồng đội đã chạm trán với Orochimaru. Orochimaru vì khao khát có được Sharingan nên đã đặt dấu ấn lên Sasuke. Dấu ấn giúp Sasuke có được sức mạnh vượt trội. Một khoảng thời gian sau, dấu ấn giúp Sasuke có được sức mạnh vượt trội. Khi Sasuke gặp lại anh trai của mình, Uchiha itachi, Itachi đã trỗi dậy sự thù hận trong Sasuke. Sasuke quyết định rời bỏ làng Lá, đi theo Orochimaru để nâng cao sức mạnh của bản thân. Trong Phần 2, Sasuke đã hấp thụ Ỏrochimaru, tự lập một nhóm riêng tên Hebi bao gồm Karin, Suigetsu, Juugo. Nhóm được lập ra để truy tìm Itachi. Sau cái chết của Itachi cậu mới biết sự thật quanh vụ tàn sát bộ tộc Uchiha: rằng mọi việc được thực hiện là do ý muốn của Hokage và Danzo, những lãnh đạo làng lo ngại sự lớn mạnh, làm phản của tộc Uchiha, nên đã ra mật lệnh cho Itachi, một gián điệp hai mang tàn sát chính gia tộc của mình. Itachi, vì không muốn chiến tranh xảy ra, đã hi sinh chính bản thân, phạm tội ác diệt tộc. Nhưng anh lại không thể xuống tay với Sasuke, đứa em trai bé bỏng của mình... Vì sự ân hận, Itachi bị bệnh tật dày vò... Anh chết trong trận chiến với Sasuke, sau khi truyền hết nhẫn thuật cho cậu...[19]. Cái chết của Itachi khiến Sasuke dường như thức tỉnh. Sau khi biết hết sự thật về Itachi được kể bởi Tobi, một kẻ tự nhận là Uchiha Madara, Sasuke quyết tâm tiêu diệt làng Lá, tiêu diệt kẻ đầu xỏ đã ra lệnh Itachi thảm sát cả gia tộc là Danzo. Sasuke sau đó được Tobi giới thiệu vào Akatsuki, với nhiệm vụ đầu tiên là bắt Bát Vĩ Khổng Ngưu đang trong cơ thể Killer Bêe thuộc làng Mây.
</p>
<h4>Tính cách</h4>
<div class="image-wiki" style="float: left">
    <img src="wiki/Uchiha_Sasuke/sasuke_2.gif">
</div>
<p>
    Khi xuất hiện lần đầu trong một nhiệm vụ cùng nhóm 7, Sasuke cho thấy sự khác biêt rất lớn với đồng đội. Cảm thấy khả năng của mình quá cao siêu so với họ, cậu không muốn hợp tác với Uzumaki Naruto hay Haruno sakura, vì làm vậy sẽ không giúp gì cho cậu trong việc giết Itachi.[20] Ý thức này nhanh chóng tỏ ra sai lạc, vì dù có thất bại, Sakura là một nguồn thông tin hữu hiệu; trong khi việc đua tranh với Naruto là một cách hiệu quả để cậu mạnh lên.[21] Trong khi cậu vẫn tỏ ra tự tin bản thân, thì Sasuke ngày càng dựa dẫm vào đồng đội khi phấn 1 tiếp diễn, Vào lúc cậu bắt đầu gần gũi với họ thì cậu cũng bắt đầu liều mạng vì họ, mặc dù cái chết của cậu sẽ khiến cho mục tiêu trả thù Itachi không thành công.[22]
</p>
<p>
    Dù Sasuke chấp nhận một cuộc sống vui vẻ trong làng Lá, cậu chưa bao giờ để khát vọng của mình có thể rời bỏ ý nghĩ báo thù. Trong các cuộc chiến ở Phần 1 với những nhân vật như Haku và Gaara, Sasuke kiểm nghiệm khả năng của mình với những ninja mạnh hơn, trong lúc đó khám phá ra những điểm yếu để khắc phục.[23] Cùng với sự hài lòng ban đầu về sự phát triển của mình, Naruto nhanh chóng trở nên mạnh hơn với tốc độ hơn hẳn. Điều này, cùng với việc bị Itachi đánh cho tơi tả trong một chuyến hồi hương về làng Lá, khiến cho Sasuke tin rằng sự tiến bộ của cậu vẫn còn chậm. Để định mức lại sức mạnh của mình, cậu bắt đầu coi bạn của mình là đối thủ để kiểm nghiệm khả năng của mình với họ.[24].
</p>
<p>
    Không hài lòng với sự tiến bộ của mình ở làng Lá và tin rằng Orochimaru giữ chìa khóa để giúp cậu có sức mạnh giết Itachi, Sasuke rời bỏ làng Lá vào cuối Phần I.[25] Naruto cố gắng chặn cậu nhưng Sasuke, tin rằng cái chết của Naruto, người bạn thân nhất của mình, sẽ cho cậu sức mạnh cậu mong muốn (như cậu được Itachi bảo), thay vào đó lại cố giết Naruto.[18] Cậu lại hoàn toàn không thể đi theo ý nghĩ này, vì cậu cảm thấy đó là điều Itachi muốn cậu làm, và thay vào đó lại đi theo Orochimaru.[26] Trong 2 năm luyện tập cùng Orochimaru, mục tiêu giết Itachi của Sasuke trào dâng hơn mọi thứ khác; cậu còn tự nguyện hiến dâng thân xác của mình cho Orochimaru nếu điều đó có nghĩa là giết được Itachi. Nhưng thực ra là Sasuke muốn lừa Orochimaru để lão giúp cậu mạnh lên [27] nhưng về sau cậu lại ám sát Orochimaru khi hắn đang ở trong tình trạng yếu nhất. Sau đó Sasuke thành lập 1 nhóm ninja độc lập gồm những ninja từng là tù nhân của Orochimaru để đạt được mục đích của mình, gồm: Suigetsu, Juugo và Karin với tên gọi là Rắn.[28] Sau khi đạt được mục đích tiêu diệt Itachi, cùng lúc đó cậu biết được hành động giết cả tộc Uchiha của anh trai mình ngày xưa bị cấp trên của làng Lá điều khiển, Sasuke nghe được tin đó thì vô cùng đau khổ và buồn bã và tức giận, quyết định từ bỏ mọi lòng căm thù với anh trai mình và giải quyết bằng cách quyết phá hủy làng Lá để trả thù cho anh trai của mình. Lúc đó, Sasuke thay đổi tên nhóm thành Đại Bàng để phù hợp hơn với mục tiêu sắp tới và liên minh với Akatsuki. Hiện tại Sasuke đã có được đôi mắt của anh trai Itachi nhờ sự giúp đỡ của Tobi[29]
</p>
<h4>Khả năng</h4>
<div class="image-wiki" style="float: right">
    <img src="wiki/Uchiha_Sasuke/sasuke_3.jpg">
</div>
<p>
    Sasuke luôn có thể nắm được thuật ninja dễ dàng. Khi truyện Nảruto bắt đầu Sasuke cực kỳ thành thạo với thuật hỏa độn và vũ khí riêng biệt của Uchiha,[30]. Trong các khả năng cậu có được nhờ dòng máu Uchiha, Sasuke thường sử dụng Sharingan một thuật hoạt động qua đôi mắt, giúp cậu có được nhiều lợi thế. Sharingan của Sasuke phát triển trong Phần 1, lúc đầu chỉ giúp cậu theo dõi các vật chuyển động nhanh[31] và dự đoán chuyển động của đối phương.[32] Trong Phần 2 cậu bắt đầu dùng Sharingan để niệm ảo thuật, giúp cậu điều khiển và làm rối trí đối phương.[33] Sharingan của Sasuke đạt đến đỉnh điểm sau cái chết của Itachi; qua cái chết của người thân nhất với cậu, Sasuke đã đánh thức Vạn Hoa Đồng Sharingan của riêng cậu,[34] cho cậu thuật lửa Thiên Chiếu của anh trai
</p>
<p>
    Ảnh hưởng của Orochimaru cũng là yếu tố thường gặp trong khả năng của Sasuke. Trong cuộc chạm trán đầu tiên ở Phần 1, Sasuke bị khắc dấu ấn, nó giúp cậu có sức mạnh và thú huyết dâng trào khi kích hoạt, vừa nâng cấp lên thành Ma Có Cánh cậu lao vào tấn công Naruto ngay.[35] Việc sử dụng nhiều dấu ấn của Sasuke khiến cậu càng khao khát hơn sức mạnh của nó khi cậu bước vào hình dạng Ma Có Cánh và có sức mạnh tăng cường cùng vẻ ngoài thay đổi.[36] Itachi xóa bỏ chú ấn của Orochimaru và chính hắn khỏi cơ thể Sasuke trong trận đấu cuối cùng.[19] Khi Sasuke bắt đầu tập luyện dưới trướng Orochimaru, sức mạnh của cậu tăng lên đáng kể[37] và cậu học cách triệu tập rắn để giúp cậu trong trận chiến.[38] Ngoài những thuật được dạy, Sasuke có vài khả năng của Orochimaru trong thời gian hắn nhập vào cơ thể Sasuke; Sasuke có thể hồi phục vết thương trong khoảng thời gian ngắn và nhả ngược trở ra cơ thể mới cho chính cậu.[39]
</p>
<p>
    Trước khi Sasuke rời bỏ làng, giáo viên của cậu, Hatake Kakashi đã dạy cách dùng Lôi Thiết, một chiêu đòi hỏi sự thông minh sáng tạo [24] Trong khi Sasuke có thể dùng Lôi Thiết 2 lần 1 ngày trong Phần 1, số lần sử dụng trong phần 2 vẫn chưa rõ.[40] Thay vào đó, Sasuke tận dụng biến thể của thuật, sử dụng bí quyết đằng sau Lôi Thiết để tạo ra vài thuật mới. Sự xuất hiện đầu tiên của khả năng như vậy bao gồm thuật phát ra điện quanh cơ thể làm lá chắn (Lôi Thiết Lưu - Chidori Nagashi) và thuật đưa chakra lôi độn dọc theo lưỡi kiếm Chokuto để tăng độ sắc bén của nó-thuật cải tiến này của Sasuke thực ra chưa thấy phát huy hiệu quả nhiều, bằng chứng là ứng dụng duy nhất của nó là đâm được Yamato 1 kiếm và Orochimaru 1 kiếm trong cả phần 2. Đến khi Sasuke giao đấu với Killer Bee, người cũng có khả năng truyền sét vào kiếm, thì chiêu này mất tác dụng hoàn toàn.[41] Về sau cậu còn tỏ ra có thể biến chkara lôi độn thành một dạng rắn chắc như một thanh kiếm dài,[28] và thậm chí còn khai thác chakra lôi độn cho một đòn tấn công tên Kỳ Lân. Tuy nhiên, Kỳ Lân có nhược điểm chết người là tốn rất nhiều công sức và thời gian để chuẩn bị và đối thủ không dễ gì đứng 1 chỗ nhìn. Kỳ Lân được Sasuke tặng cho Itachi[42] Con mắt của Itachi được Uchiha Obito cấy vào cho Sasuke do mắt của Sasuke đã yếu đi sau khi đấu với Danzo. Điều này giúp cho Sasuke có được Vạn hoa đồng Sharingan vĩnh cửu. Và hiện nay khi đấu với Madara, Sharingan của Sasuke đã nâng cấp lên được Sharinnegan nhờ vào Âm tiên lực mà Lục đạo hiền nhân đã truyền cho cậu. Ngoài ra, Sasuke cũng có được Susanoo toàn chân thể nhờ Sharinnegan.
</p>